version: "3.7"
name: migueloliveiradev
services:
   migueloliveiradev:
      container_name: migueloliveiradev
      image: migueloliveiradev
      env_file: .env
      build: 
          context: ./migueloliveiradev
          dockerfile: Dockerfile
      restart: always
      environment:
          - TZ=America/Sao_Paulo
      deploy:
          resources:
              limits:
                  memory: 1G