version: "3.7"
name: migueloliveiradev
services:
    migueloliveiradev:
        container_name: migueloliveiradev
        image: migueloliveiradev
        build:
            context: ./migueloliveiradev
            dockerfile: Dockerfile
        restart: always
        env_file: migueloliveiradev/.env
        ports:
            - 5152:5152
        environment:
            - TZ=America/Sao_Paulo
            - ASPNETCORE_URLS=http://+:5152
            - ASPNETCORE_ENVIRONMENT=Production
        networks:
            - database
            - nginx
        deploy:
            resources:
                limits:
                    memory: 1G
networks:
    database:
        name: database
        external: true
    nginx:
        name: nginx
        external: true